/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    posts: Post;
    pages: Page;
    people: Person;
    users: User;
  };
  globals: {};
}
export interface Post {
  id: string;
  title?: string;
  number?: number;
  myArray?: {
    subField?: string;
    id?: string;
  }[];
  relationHasOne?: string | Page;
  relationHasMany?: string[] | Page[];
  relationHasOnePoly?:
    | {
        value: string | Person;
        relationTo: 'people';
      }
    | {
        value: string | Page;
        relationTo: 'pages';
      };
  relationHasManyPoly?:
    | (
        | {
            value: string;
            relationTo: 'people';
          }
        | {
            value: string;
            relationTo: 'pages';
          }
      )[]
    | (
        | {
            value: Person;
            relationTo: 'people';
          }
        | {
            value: Page;
            relationTo: 'pages';
          }
      )[];
  myGroup?: {
    subField?: string;
    subFieldLocalized?: string;
    subGroup?: {
      subSubField?: string;
      subSubFieldLocalized?: string;
    };
  };
  updatedAt: string;
  createdAt: string;
}
export interface Page {
  id: string;
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Person {
  id: string;
  fullName?: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
